import { decideLeave } from "@/lib/actions";
import { createFileRoute } from "@tanstack/react-router";
import { ModulePage, meta } from "@/components/app/Module";
import { DataTable } from "@/components/app/DataTable";
import { StatusBadge, Section } from "@/components/app/kit";
import { leaveRequests, employees, fmtDate, KPI, SITES } from "@/data/mock";
import { useStore, emit, undoToast } from "@/lib/store";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

export const Route = createFileRoute("/_app/conges")({ head: () => meta("Congés & absences", "Calendrier d'équipe, demandes, soldes et absentéisme."), component: Page });
const HOLIDAYS = [["1er janvier", "Nouvel an"], ["11 janvier", "Manifeste de l'indépendance"], ["14 janvier", "Nouvel an amazigh"], ["1er mai", "Fête du travail"], ["30 juillet", "Fête du Trône"], ["14 août", "Oued Ed-Dahab"], ["20 août", "Révolution du Roi et du peuple"], ["21 août", "Fête de la jeunesse"], ["6 novembre", "Marche verte"], ["18 novembre", "Fête de l'indépendance"], ["Variable", "Aïd al-Fitr, Aïd al-Adha, 1er Moharram, Mawlid"]];

function Page() {
  useStore();
  const set = (r: (typeof leaveRequests)[number], s: string) => decideLeave([r.id], s as "Approuvée" | "Refusée");
  return (
    <ModulePage title="Congés & absences" subtitle="Zgounder en rotation (équipes A–D, 3x8) · Siège et Marrakech en horaires standard"
      kpis={[{ label: "En congé aujourd'hui", value: KPI.onLeave }, { label: "Demandes en attente", value: KPI.pendingLeave }, { label: "Absentéisme", value: 3.1, decimals: 1, suffix: " %" }, { label: "Certificats manquants", value: 4 }]}
      actions={[{ label: "Nouvelle demande", primary: true, fields: [{ name: "t", label: "Type", type: "select", options: ["Congé annuel", "Maladie", "Maternité/paternité", "Événement familial", "Sans solde", "Formation"], required: true }, { name: "s", label: "Du", type: "date", required: true }, { name: "e", label: "Au", type: "date", required: true }, { name: "h", label: "Demi-journée", type: "select", options: ["Non", "Matin", "Après-midi"] }, { name: "m", label: "Motif", type: "textarea" }], ai: "Vérifications automatiques : solde suffisant (18 j) · aucun conflit d'équipe · effectif minimum équipe B respecté · aucune formation critique sur la période.", confirm: "Soumettre", success: "Demande envoyée au manager" }, { label: "Ajustement de soldes en lot", fields: [{ name: "n", label: "Nombre de jours (+/-)", type: "number", required: true }, { name: "r", label: "Motif", required: true }], success: "Soldes ajustés — entrée ajoutée au journal d'audit" }]}
      tabs={[
        { label: "Calendrier d'équipe", content: <Section title="Heatmap des absences — 12 mois"><div className="grid grid-cols-12 gap-1" role="img" aria-label="Carte de chaleur des absences par jour">{Array.from({ length: 12 * 28 }).map((_, i) => { const v = (Math.sin(i * 0.7) + Math.sin(i * 0.13) + 2) / 4; return <span key={i} className={cn("h-3 rounded-sm", v > 0.75 ? "bg-gold" : v > 0.55 ? "bg-gold/60" : v > 0.35 ? "bg-gold/30" : "bg-muted")} />; })}</div><div className="mt-2 grid grid-cols-12 text-center text-[10px] text-muted-foreground">{["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"].map((m, i) => <span key={i}>{m}</span>)}</div></Section> },
        { label: "Demandes", content: <DataTable id="lv" rows={leaveRequests} filters={[{ key: "status", label: "Statut", options: ["En attente", "Approuvée", "Refusée"] }, { key: "type", label: "Type", options: ["Congé annuel", "Maladie", "Événement familial", "Sans solde", "Formation", "Maternité/paternité"] }, { key: "site", label: "Site", options: [...SITES] }]}
          rowActions={(r) => [{ label: "Approuver", onClick: () => set(r, "Approuvée") }, { label: "Demander des précisions", onClick: () => toast.success("Demande de précisions envoyée") }, { label: "Refuser", onClick: () => { const m = prompt("Motif du refus :"); if (m) set(r, "Refusée"); }, danger: true }]}
          bulkActions={(ids, clear) => <button className="rounded-md bg-primary px-3 py-1.5 text-sm text-primary-foreground" onClick={() => { decideLeave(ids, "Approuvée"); clear(); }}>Approuver</button>}
          columns={[{ key: "id", header: "Réf." }, { key: "emp", header: "Collaborateur" }, { key: "site", header: "Site" }, { key: "type", header: "Type" }, { key: "start", header: "Début", render: (r) => fmtDate(r.start) }, { key: "days", header: "Jours" }, { key: "status", header: "Statut", render: (r) => <StatusBadge label={r.status} /> }]} /> },
        { label: "Soldes", content: <DataTable id="bal" rows={employees.map((e, i) => ({ id: e.id, name: e.name, site: e.site, contract: e.contract, annual: 18 + (i % 9), taken: i % 14, carry: i % 5 }))} defaultPageSize={25} columns={[{ key: "name", header: "Collaborateur" }, { key: "site", header: "Site" }, { key: "contract", header: "Contrat" }, { key: "annual", header: "Acquis" }, { key: "taken", header: "Pris" }, { key: "carry", header: "Report" }, { key: "rest", header: "Solde", value: (r) => r.annual + r.carry - r.taken, render: (r) => <b className="tnum">{r.annual + r.carry - r.taken} j</b> }]} /> },
        { label: "Absences", content: <><p className="rounded-lg bg-warning/10 p-3 text-sm text-warning">Alerte récurrence : 3 collaborateurs présentent des absences répétées le lundi.</p><DataTable id="abs" rows={leaveRequests.filter((l) => l.type === "Maladie").map((l, i) => ({ ...l, cert: ["Reçu", "Manquant", "Hors délai", "Reçu"][i % 4] }))} rowActions={(r) => [{ label: "Planifier un entretien de retour", onClick: () => toast.success(`Entretien de retour planifié avec ${r.emp}`) }]} columns={[{ key: "emp", header: "Collaborateur" }, { key: "site", header: "Site" }, { key: "start", header: "Début", render: (r) => fmtDate(r.start) }, { key: "days", header: "Jours" }, { key: "cert", header: "Certificat", render: (r) => <StatusBadge label={r.cert} /> }]} /></> },
        { label: "Règles", content: <div className="grid gap-4 md:grid-cols-2"><Section title="Jours fériés (Maroc)">{HOLIDAYS.map(([d, n]) => <p key={n} className="flex justify-between border-b border-border py-1.5 text-sm"><span>{n}</span><span className="text-muted-foreground">{d}</span></p>)}</Section><Section title="Règles d'acquisition">{[["CDI", "1,5 j ouvrable / mois + 1,5 j par tranche de 5 ans"], ["CDD", "1,5 j / mois au prorata"], ["Intérim", "Selon agence"], ["Stage", "Non applicable"]].map(([k, v]) => <p key={k} className="flex justify-between border-b border-border py-1.5 text-sm"><b>{k}</b><span className="text-muted-foreground">{v}</span></p>)}</Section></div> },
      ]} />
  );
}
