import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Bar as RBar, BarChart, CartesianGrid, Legend, PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ModulePage, meta, ActionButtons } from "@/components/app/Module";
import { DataTable } from "@/components/app/DataTable";
import { StatusBadge, Glass, Section, Bar, Typing, AiDisclaimer } from "@/components/app/kit";
import { trainings, sessions, DEPTS, fmtDate, fmtMAD, employees, KPI } from "@/data/mock";
import { exportPdf } from "@/lib/pdf";
import { toast } from "sonner";

export const Route = createFileRoute("/_app/formation")({ head: () => meta("Formation", "Plan de formation, sessions, budget et programme IA."), component: Page });
const tip = { contentStyle: { background: "var(--popover)", border: "1px solid var(--border)", borderRadius: 8, fontSize: 12 } };
const budget = DEPTS.map((d, i) => { const p = Math.round((KPI.training.budget / DEPTS.length) * (0.6 + (i % 4) * 0.25)); return { d: d.split(" ")[0], Prévu: p, Consommé: Math.round(p * [0.55, 0.62, 0.93, 0.48, 0.7, 0.58][i % 6]) }; });
const AGENTS = [["Assistant planning 3x8", "Production minière", "Génère les plannings de rotation", "6 h / semaine"], ["Analyseur de rapports HSE", "HSE", "Classe les incidents et propose des actions", "4 h / semaine"], ["Rédacteur d'appels d'offres", "Approvisionnement & achats", "Prépare les cahiers des charges", "5 h / semaine"], ["Contrôle factures", "Finance & comptabilité", "Rapproche factures et bons de commande", "8 h / semaine"]];

function Page() {
  const [emp, setEmp] = useState(employees[5].id);
  const e = employees.find((x) => x.id === emp)!;
  return (
    <ModulePage title="Formation" subtitle={`Budget annuel ${fmtMAD(KPI.training.budget)} · consommé ${KPI.training.consumed} %`}
      kpis={[{ label: "Sessions planifiées", value: KPI.training.sessions }, { label: "Formés depuis janvier", value: KPI.training.trained }, { label: "Budget consommé", value: KPI.training.consumed, suffix: " %" }, { label: "Réalisation du plan", value: KPI.training.realization, suffix: " %", ring: 85 }, { label: "Agents IA créés", value: 27 }]}
      actions={[{ label: "Créer une session", primary: true, fields: [{ name: "c", label: "Formation", type: "select", options: trainings.map((t) => t.title), required: true }, { name: "d", label: "Date", type: "date", required: true }, { name: "t", label: "Formateur", required: true }, { name: "p", label: "Lieu", type: "select", options: ["Zgounder", "Boumadine", "Marrakech", "Siège"] }, { name: "cap", label: "Capacité", type: "number", def: "12" }], confirm: "Créer", success: "Session créée — 2 conflits détectés (congés, quart de nuit)" }, { label: "Ajouter un besoin", fields: [{ name: "b", label: "Besoin", required: true }, { name: "d", label: "Département", type: "select", options: DEPTS }, { name: "p", label: "Priorité", type: "select", options: ["Haute", "Moyenne", "Basse"] }], success: "Besoin ajouté au plan" }]}
      tabs={[
        { label: "Plan de formation", content: <Section title="Plan annuel par département">{budget.map((b) => <div key={b.d} className="mb-3"><div className="flex justify-between text-sm"><span>{b.d}</span><span className="tnum text-muted-foreground">{fmtMAD(b.Consommé)} / {fmtMAD(b.Prévu)}</span></div><Bar value={b.Consommé} max={b.Prévu} tone={b.Consommé / b.Prévu > 0.9 ? "danger" : "gold"} /></div>)}</Section> },
        { label: "Catalogue", content: <DataTable id="cat" rows={trainings} filters={[{ key: "category", label: "Catégorie", options: ["HSE", "Technique", "Management", "Digital & IA", "Langues"] }]} cards={(t) => <Glass className="p-4"><StatusBadge label={t.category} tone="info" /><p className="mt-2 font-semibold">{t.title}</p><p className="text-xs text-muted-foreground">{t.duration} · {t.provider} · {fmtMAD(t.cost)}</p></Glass>} columns={[{ key: "id", header: "Réf." }, { key: "title", header: "Intitulé" }, { key: "category", header: "Catégorie", render: (t) => <StatusBadge label={t.category} tone="info" /> }, { key: "duration", header: "Durée" }, { key: "provider", header: "Organisme" }, { key: "cost", header: "Coût", render: (t) => fmtMAD(t.cost) }, { key: "prereq", header: "Prérequis" }]} /> },
        { label: "Sessions", content: <DataTable id="ses" rows={sessions} drawerTitle={(s) => s.course} drawer={(s) => <div className="space-y-3 text-sm"><p>{fmtDate(s.date)} · {s.place} · formateur {s.trainer}</p><p>{s.registered} / {s.capacity} inscrits</p><p className="rounded bg-warning/10 p-2 text-xs text-warning">2 conflits : 1 congé, 1 habilitation prérequise expirée</p><div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => toast.success("Convocations envoyées")}>Envoyer les convocations</Button><Button size="sm" variant="outline" onClick={() => toast.success("Feuille de présence enregistrée")}>Feuille de présence</Button><Button size="sm" variant="outline" onClick={() => toast.success("Évaluation à chaud envoyée")}>Évaluation à chaud</Button><Button size="sm" variant="outline" onClick={() => exportPdf(`Attestation de formation — ${s.course}`, [["Formation", `${s.course} — ${fmtDate(s.date)} — ${s.place}`]])}>Certificats PDF</Button><Button size="sm" variant="outline" onClick={() => toast.success("Session clôturée")}>Clôturer</Button></div></div>} columns={[{ key: "id", header: "Réf." }, { key: "course", header: "Formation" }, { key: "date", header: "Date", render: (s) => fmtDate(s.date) }, { key: "place", header: "Lieu" }, { key: "trainer", header: "Formateur" }, { key: "registered", header: "Inscrits", render: (s) => `${s.registered}/${s.capacity}` }, { key: "status", header: "Statut", render: (s) => <StatusBadge label={s.status} /> }]} /> },
        { label: "Demandes", content: <DataTable id="treq" rows={employees.slice(10, 40).map((e, i) => ({ id: `DF-${i + 1}`, emp: e.name, site: e.site, course: trainings[i % 36].title, status: ["En attente manager", "En attente RH", "Approuvée", "Refusée"][i % 4] }))} rowActions={() => [{ label: "Approuver", onClick: () => toast.success("Demande approuvée") }, { label: "Refuser", onClick: () => toast("Demande refusée"), danger: true }]} columns={[{ key: "id", header: "Réf." }, { key: "emp", header: "Collaborateur" }, { key: "site", header: "Site" }, { key: "course", header: "Formation" }, { key: "status", header: "Statut", render: (r) => <StatusBadge label={r.status} /> }]} /> },
        { label: "Budget", content: <Section title="Prévu vs consommé par département">{budget.some((b) => b.Consommé / b.Prévu > 0.9) && <p className="mb-3 rounded-lg bg-danger/10 p-2 text-xs text-danger">Alerte : {budget.filter((b) => b.Consommé / b.Prévu > 0.9).map((b) => b.d).join(", ")} au-delà de 90 % du budget.</p>}<div className="h-72" role="img" aria-label="Budget formation prévu et consommé par département"><ResponsiveContainer><BarChart data={budget}><CartesianGrid stroke="var(--border)" vertical={false} /><XAxis dataKey="d" stroke="var(--muted-foreground)" fontSize={10} /><YAxis stroke="var(--muted-foreground)" fontSize={10} /><Tooltip {...tip} /><Legend /><RBar dataKey="Prévu" fill="var(--silver)" radius={[4, 4, 0, 0]} /><RBar dataKey="Consommé" fill="var(--gold)" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></Section> },
        { label: "Formation IA", content: <div className="grid gap-4 lg:grid-cols-2">
          <Section title="Cohortes du programme compétences IA">{[["Cohorte 1 — Managers", 24, 96], ["Cohorte 2 — Support", 32, 81], ["Cohorte 3 — Sites", 40, 54]].map(([c, n, p]) => <div key={c as string} className="mb-3"><div className="flex justify-between text-sm"><span>{c} · {n} participants</span><b>{p} %</b></div><Bar value={p as number} /></div>)}</Section>
          <Section title="Maturité IA par département"><div className="h-64" role="img" aria-label="Radar de maturité IA"><ResponsiveContainer><RadarChart data={DEPTS.slice(0, 7).map((d, i) => ({ d: d.split(" ")[0], v: 30 + ((i * 17) % 60) }))}><PolarGrid stroke="var(--border)" /><PolarAngleAxis dataKey="d" tick={{ fill: "var(--muted-foreground)", fontSize: 10 }} /><Radar dataKey="v" stroke="var(--gold)" fill="var(--gold)" fillOpacity={0.25} /></RadarChart></ResponsiveContainer></div></Section>
          <Section title="Agents IA créés par les collaborateurs" className="lg:col-span-2"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-muted-foreground"><th>Agent</th><th>Département</th><th>Cas d'usage</th><th>Temps gagné</th></tr></thead><tbody>{AGENTS.map((a) => <tr key={a[0]} className="border-t border-border">{a.map((x) => <td key={x} className="py-2">{x}</td>)}</tr>)}</tbody></table></Section>
        </div> },
        { label: "Recommandations", content: <Section title="Recommander des formations" action={<select value={emp} onChange={(x) => setEmp(x.target.value)} className="rounded-md border border-input bg-background px-2 py-1 text-sm">{employees.slice(0, 60).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select>}>
          <p className="mb-3 flex items-center gap-1 text-sm text-gold"><Sparkles className="h-4 w-4" />Suggestions pour {e.name} ({e.job})</p>
          {[[trainings[0].title, "Habilitation requise par la fiche de poste, expire dans 45 jours"], [trainings[5].title, "Écart de compétences numériques identifié lors de l'entretien annuel"], [trainings[7].title, "Recommandé pour l'évolution vers chef d'équipe"]].map(([t, r]) => <div key={t} className="mb-2 flex items-center justify-between rounded-lg border border-border p-3"><div><p className="font-medium">{t}</p><p className="text-xs text-muted-foreground"><Typing text={r} /></p></div><Button size="sm" onClick={() => toast.success(`${e.name} inscrit(e)`)}>Inscrire</Button></div>)}<AiDisclaimer />
        </Section> },
      ]} />
  );
}
export { ActionButtons };
