/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDemandesDePosteRouteImport } from './routes/_app/demandes-de-poste'
import { Route as AppEntretiensRouteImport } from './routes/_app/entretiens'
import { Route as AppOffresRouteImport } from './routes/_app/offres'
import { Route as AppVivierRouteImport } from './routes/_app/vivier'
import { Route as AppCandidaturesIndexRouteImport } from './routes/_app/candidatures.index'
import { Route as AppCandidaturesIdRouteImport } from './routes/_app/candidatures.$id'
import { Route as AppFichesDePosteIndexRouteImport } from './routes/_app/fiches-de-poste.index'
import { Route as AppFichesDePosteIdRouteImport } from './routes/_app/fiches-de-poste.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandesDePosteRoute = AppDemandesDePosteRouteImport.update({
  id: '/demandes-de-poste',
  path: '/demandes-de-poste',
  getParentRoute: () => AppRoute,
} as any)
const AppEntretiensRoute = AppEntretiensRouteImport.update({
  id: '/entretiens',
  path: '/entretiens',
  getParentRoute: () => AppRoute,
} as any)
const AppOffresRoute = AppOffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => AppRoute,
} as any)
const AppVivierRoute = AppVivierRouteImport.update({
  id: '/vivier',
  path: '/vivier',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidaturesIndexRoute = AppCandidaturesIndexRouteImport.update({
  id: '/candidatures/',
  path: '/candidatures/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidaturesIdRoute = AppCandidaturesIdRouteImport.update({
  id: '/candidatures/$id',
  path: '/candidatures/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFichesDePosteIndexRoute = AppFichesDePosteIndexRouteImport.update({
  id: '/fiches-de-poste/',
  path: '/fiches-de-poste/',
  getParentRoute: () => AppRoute,
} as any)
const AppFichesDePosteIdRoute = AppFichesDePosteIdRouteImport.update({
  id: '/fiches-de-poste/$id',
  path: '/fiches-de-poste/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/demandes-de-poste': typeof AppDemandesDePosteRoute
  '/entretiens': typeof AppEntretiensRoute
  '/offres': typeof AppOffresRoute
  '/vivier': typeof AppVivierRoute
  '/candidatures/$id': typeof AppCandidaturesIdRoute
  '/fiches-de-poste/$id': typeof AppFichesDePosteIdRoute
  '/candidatures/': typeof AppCandidaturesIndexRoute
  '/fiches-de-poste/': typeof AppFichesDePosteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/demandes-de-poste': typeof AppDemandesDePosteRoute
  '/entretiens': typeof AppEntretiensRoute
  '/offres': typeof AppOffresRoute
  '/vivier': typeof AppVivierRoute
  '/candidatures/$id': typeof AppCandidaturesIdRoute
  '/fiches-de-poste/$id': typeof AppFichesDePosteIdRoute
  '/candidatures': typeof AppCandidaturesIndexRoute
  '/fiches-de-poste': typeof AppFichesDePosteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/demandes-de-poste': typeof AppDemandesDePosteRoute
  '/_app/entretiens': typeof AppEntretiensRoute
  '/_app/offres': typeof AppOffresRoute
  '/_app/vivier': typeof AppVivierRoute
  '/_app/candidatures/$id': typeof AppCandidaturesIdRoute
  '/_app/fiches-de-poste/$id': typeof AppFichesDePosteIdRoute
  '/_app/candidatures/': typeof AppCandidaturesIndexRoute
  '/_app/fiches-de-poste/': typeof AppFichesDePosteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demandes-de-poste'
    | '/entretiens'
    | '/offres'
    | '/vivier'
    | '/candidatures/$id'
    | '/fiches-de-poste/$id'
    | '/candidatures/'
    | '/fiches-de-poste/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/demandes-de-poste'
    | '/entretiens'
    | '/offres'
    | '/vivier'
    | '/candidatures/$id'
    | '/fiches-de-poste/$id'
    | '/candidatures'
    | '/fiches-de-poste'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/demandes-de-poste'
    | '/_app/entretiens'
    | '/_app/offres'
    | '/_app/vivier'
    | '/_app/candidatures/$id'
    | '/_app/fiches-de-poste/$id'
    | '/_app/candidatures/'
    | '/_app/fiches-de-poste/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demandes-de-poste': {
      id: '/_app/demandes-de-poste'
      path: '/demandes-de-poste'
      fullPath: '/demandes-de-poste'
      preLoaderRoute: typeof AppDemandesDePosteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entretiens': {
      id: '/_app/entretiens'
      path: '/entretiens'
      fullPath: '/entretiens'
      preLoaderRoute: typeof AppEntretiensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offres': {
      id: '/_app/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof AppOffresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vivier': {
      id: '/_app/vivier'
      path: '/vivier'
      fullPath: '/vivier'
      preLoaderRoute: typeof AppVivierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidatures/': {
      id: '/_app/candidatures/'
      path: '/candidatures'
      fullPath: '/candidatures/'
      preLoaderRoute: typeof AppCandidaturesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidatures/$id': {
      id: '/_app/candidatures/$id'
      path: '/candidatures/$id'
      fullPath: '/candidatures/$id'
      preLoaderRoute: typeof AppCandidaturesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiches-de-poste/': {
      id: '/_app/fiches-de-poste/'
      path: '/fiches-de-poste'
      fullPath: '/fiches-de-poste/'
      preLoaderRoute: typeof AppFichesDePosteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiches-de-poste/$id': {
      id: '/_app/fiches-de-poste/$id'
      path: '/fiches-de-poste/$id'
      fullPath: '/fiches-de-poste/$id'
      preLoaderRoute: typeof AppFichesDePosteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDemandesDePosteRoute: typeof AppDemandesDePosteRoute
  AppEntretiensRoute: typeof AppEntretiensRoute
  AppOffresRoute: typeof AppOffresRoute
  AppVivierRoute: typeof AppVivierRoute
  AppCandidaturesIdRoute: typeof AppCandidaturesIdRoute
  AppFichesDePosteIdRoute: typeof AppFichesDePosteIdRoute
  AppCandidaturesIndexRoute: typeof AppCandidaturesIndexRoute
  AppFichesDePosteIndexRoute: typeof AppFichesDePosteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDemandesDePosteRoute: AppDemandesDePosteRoute,
  AppEntretiensRoute: AppEntretiensRoute,
  AppOffresRoute: AppOffresRoute,
  AppVivierRoute: AppVivierRoute,
  AppCandidaturesIdRoute: AppCandidaturesIdRoute,
  AppFichesDePosteIdRoute: AppFichesDePosteIdRoute,
  AppCandidaturesIndexRoute: AppCandidaturesIndexRoute,
  AppFichesDePosteIndexRoute: AppFichesDePosteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
